export const treeNodes = [
  {
    id: "defbbbb0b34c11eeb6150242bae6ed32",
    parent: "",
    text: "Phòng TCLĐ - Khối cơ quan",
    address: null,
    type: 0,
    textEn: null,
    permissionType: 0,
    cameraLimited: null,
    cameraNumber: null,
    provinceId: null,
    districtId: null,
    wardId: null,
    phone: null,
    email: null,
    createDate: null,
    lastModifiedDate: null,
    accessKey: null,
    secretKey: null,
    capacity: 0,
  },
  {
    id: "17f2b5e0b34d11eea61bbaf7db86dba7",
    parent: "",
    text: "TT Nghiên cứu thiết bị y tế - Khối 2",
    address: null,
    type: 0,
    textEn: null,
    permissionType: 0,
    cameraLimited: null,
    cameraNumber: null,
    provinceId: null,
    districtId: null,
    wardId: null,
    phone: null,
    email: null,
    createDate: null,
    lastModifiedDate: null,
    accessKey: null,
    secretKey: null,
    capacity: 0,
  },
  {
    id: "45ecb1703a7111efa12b024296534ac6",
    parent: "2e259700a5c111ed809502429ea8fc86",
    text: "abc",
    address: null,
    type: 0,
    textEn: null,
    permissionType: 0,
    cameraLimited: null,
    cameraNumber: null,
    provinceId: null,
    districtId: null,
    wardId: null,
    phone: null,
    email: null,
    createDate: null,
    lastModifiedDate: null,
    accessKey: null,
    secretKey: null,
    capacity: 0,
  },
  {
    id: "2e259700a5c111ed809502429ea8fc86",
    parent: "8ec2641084fd11ed94170242a040d71d",
    text: "hanh đã đổi lần 2",
    address: null,
    type: 0,
    textEn: null,
    permissionType: 0,
    cameraLimited: null,
    cameraNumber: null,
    provinceId: null,
    districtId: null,
    wardId: null,
    phone: null,
    email: null,
    createDate: null,
    lastModifiedDate: null,
    accessKey: null,
    secretKey: null,
    capacity: 0,
  },
  {
    id: "a3b79d30b34c11ee9f95024209624052",
    parent: "",
    text: "Công ty Quản lý tài sản Viettel",
    address: null,
    type: 0,
    textEn: null,
    permissionType: 0,
    cameraLimited: null,
    cameraNumber: null,
    provinceId: null,
    districtId: null,
    wardId: null,
    phone: null,
    email: null,
    createDate: null,
    lastModifiedDate: null,
    accessKey: null,
    secretKey: null,
    capacity: 0,
  },
  {
    id: "f3aebb607c7411efafe8baf7db86dba7",
    parent: "c5db63207c7211efafe8baf7db86dba7",
    text: "test270902",
    address: null,
    type: 0,
    textEn: null,
    permissionType: 0,
    cameraLimited: null,
    cameraNumber: null,
    provinceId: null,
    districtId: null,
    wardId: null,
    phone: null,
    email: null,
    createDate: null,
    lastModifiedDate: null,
    accessKey: null,
    secretKey: null,
    capacity: 0,
  },
  {
    id: "8ec2641084fd11ed94170242a040d71d",
    parent: "",
    text: "Ban Giám đốc - Khối cơ quan",
    address: null,
    type: 0,
    textEn: null,
    permissionType: 0,
    cameraLimited: null,
    cameraNumber: null,
    provinceId: null,
    districtId: null,
    wardId: null,
    phone: null,
    email: null,
    createDate: null,
    lastModifiedDate: null,
    accessKey: null,
    secretKey: null,
    capacity: 0,
  },
  {
    id: "18317e80b34b11eea61bbaf7db86dba7",
    parent: "",
    text: "Trung tâm Mô hình mô phỏng - Khối 1",
    address: null,
    type: 0,
    textEn: null,
    permissionType: 0,
    cameraLimited: null,
    cameraNumber: null,
    provinceId: null,
    districtId: null,
    wardId: null,
    phone: null,
    email: null,
    createDate: null,
    lastModifiedDate: null,
    accessKey: null,
    secretKey: null,
    capacity: 0,
  },
  {
    id: "b1022be0b34c11eeb6150242bae6ed32",
    parent: "",
    text: "Nhóm chuyên gia - Khối 1",
    address: null,
    type: 0,
    textEn: null,
    permissionType: 0,
    cameraLimited: null,
    cameraNumber: null,
    provinceId: null,
    districtId: null,
    wardId: null,
    phone: null,
    email: null,
    createDate: null,
    lastModifiedDate: null,
    accessKey: null,
    secretKey: null,
    capacity: 0,
  },
  {
    id: "c460f900b34c11eeb6150242bae6ed32",
    parent: "",
    text: "Phòng Đảm bảo chất lượng - Khối 1",
    address: null,
    type: 0,
    textEn: null,
    permissionType: 0,
    cameraLimited: null,
    cameraNumber: null,
    provinceId: null,
    districtId: null,
    wardId: null,
    phone: null,
    email: null,
    createDate: null,
    lastModifiedDate: null,
    accessKey: null,
    secretKey: null,
    capacity: 0,
  },
  {
    id: "84570a80b34b11ee9f95024209624052",
    parent: "",
    text: "Phòng Tổng hợp - Khối 1",
    address: null,
    type: 0,
    textEn: null,
    permissionType: 0,
    cameraLimited: null,
    cameraNumber: null,
    provinceId: null,
    districtId: null,
    wardId: null,
    phone: null,
    email: null,
    createDate: null,
    lastModifiedDate: null,
    accessKey: null,
    secretKey: null,
    capacity: 0,
  },
  {
    id: "59a4bcb03d9311efbb14024296534ac6",
    parent: "52f21b603d9311ef98223afdc3cd602b",
    text: "23",
    address: null,
    type: 0,
    textEn: null,
    permissionType: 0,
    cameraLimited: null,
    cameraNumber: null,
    provinceId: null,
    districtId: null,
    wardId: null,
    phone: null,
    email: null,
    createDate: null,
    lastModifiedDate: null,
    accessKey: null,
    secretKey: null,
    capacity: 0,
  },
  {
    id: "1e757f80b34b11ee9f95024209624052",
    parent: "",
    text: "Trung tâm Camera - Khối 3",
    address: null,
    type: 0,
    textEn: null,
    permissionType: 0,
    cameraLimited: null,
    cameraNumber: null,
    provinceId: null,
    districtId: null,
    wardId: null,
    phone: null,
    email: null,
    createDate: null,
    lastModifiedDate: null,
    accessKey: null,
    secretKey: null,
    capacity: 0,
  },
  {
    id: "11554a40b34d11eea61bbaf7db86dba7",
    parent: "",
    text: "TT dịch vụ sau bán hàng - Khối 1",
    address: null,
    type: 0,
    textEn: null,
    permissionType: 0,
    cameraLimited: null,
    cameraNumber: null,
    provinceId: null,
    districtId: null,
    wardId: null,
    phone: null,
    email: null,
    createDate: null,
    lastModifiedDate: null,
    accessKey: null,
    secretKey: null,
    capacity: 0,
  },
  {
    id: "2f3594d03e9311ef98223afdc3cd602b",
    parent: "59a4bcb03d9311efbb14024296534ac6",
    text: "23668",
    address: null,
    type: 0,
    textEn: null,
    permissionType: 0,
    cameraLimited: null,
    cameraNumber: null,
    provinceId: null,
    districtId: null,
    wardId: null,
    phone: null,
    email: null,
    createDate: null,
    lastModifiedDate: null,
    accessKey: null,
    secretKey: null,
    capacity: 0,
  },
  {
    id: "13911b60b34b11eeb6150242bae6ed32",
    parent: "",
    text: "Trung tâm Chỉ huy điều khiển - Khối 1",
    address: null,
    type: 0,
    textEn: null,
    permissionType: 0,
    cameraLimited: null,
    cameraNumber: null,
    provinceId: null,
    districtId: null,
    wardId: null,
    phone: null,
    email: null,
    createDate: null,
    lastModifiedDate: null,
    accessKey: null,
    secretKey: null,
    capacity: 0,
  },
  {
    id: "23230200b34b11eebe6f3afdc3cd602b",
    parent: "",
    text: "Trung tâm Vi mạch - Khối 3",
    address: null,
    type: 0,
    textEn: null,
    permissionType: 0,
    cameraLimited: null,
    cameraNumber: null,
    provinceId: null,
    districtId: null,
    wardId: null,
    phone: null,
    email: null,
    createDate: null,
    lastModifiedDate: null,
    accessKey: null,
    secretKey: null,
    capacity: 0,
  },
  {
    id: "30328380b34b11eebe6f3afdc3cd602b",
    parent: "",
    text: "TT Công nghệ CSSK - Khối 3",
    address: null,
    type: 0,
    textEn: null,
    permissionType: 0,
    cameraLimited: null,
    cameraNumber: null,
    provinceId: null,
    districtId: null,
    wardId: null,
    phone: null,
    email: null,
    createDate: null,
    lastModifiedDate: null,
    accessKey: null,
    secretKey: null,
    capacity: 0,
  },
  {
    id: "7fd6b280b34b11ee9f95024209624052",
    parent: "",
    text: "Phòng tổng hợp - Khối 3",
    address: null,
    type: 0,
    textEn: null,
    permissionType: 0,
    cameraLimited: null,
    cameraNumber: null,
    provinceId: null,
    districtId: null,
    wardId: null,
    phone: null,
    email: null,
    createDate: null,
    lastModifiedDate: null,
    accessKey: null,
    secretKey: null,
    capacity: 0,
  },
  {
    id: "bd551420b34c11ee9f95024209624052",
    parent: "",
    text: "Phòng Chính trị - Khối cơ quan",
    address: null,
    type: 0,
    textEn: null,
    permissionType: 0,
    cameraLimited: null,
    cameraNumber: null,
    provinceId: null,
    districtId: null,
    wardId: null,
    phone: null,
    email: null,
    createDate: null,
    lastModifiedDate: null,
    accessKey: null,
    secretKey: null,
    capacity: 0,
  },
  {
    id: "fc0c4b40b34a11eeb6150242bae6ed32",
    parent: "",
    text: "Trung tâm Kỹ thuật công nghệ - Khối 1",
    address: null,
    type: 0,
    textEn: null,
    permissionType: 0,
    cameraLimited: null,
    cameraNumber: null,
    provinceId: null,
    districtId: null,
    wardId: null,
    phone: null,
    email: null,
    createDate: null,
    lastModifiedDate: null,
    accessKey: null,
    secretKey: null,
    capacity: 0,
  },
  {
    id: "ccd82db0b34c11eeb6150242bae6ed32",
    parent: "",
    text: "Phòng Khoa học Công Nghệ-Chiến Lược - Khối cơ quan",
    address: null,
    type: 0,
    textEn: null,
    permissionType: 0,
    cameraLimited: null,
    cameraNumber: null,
    provinceId: null,
    districtId: null,
    wardId: null,
    phone: null,
    email: null,
    createDate: null,
    lastModifiedDate: null,
    accessKey: null,
    secretKey: null,
    capacity: 0,
  },
  {
    id: "f6104fc1b34a11ee9f95024209624052",
    parent: "",
    text: "Trung tâm Kinh doanh",
    address: null,
    type: 0,
    textEn: null,
    permissionType: 0,
    cameraLimited: null,
    cameraNumber: null,
    provinceId: null,
    districtId: null,
    wardId: null,
    phone: null,
    email: null,
    createDate: null,
    lastModifiedDate: null,
    accessKey: null,
    secretKey: null,
    capacity: 0,
  },
  {
    id: "621d23a0b34b11eea61bbaf7db86dba7",
    parent: "",
    text: "Phòng Hành chính - Khối cơ quan",
    address: null,
    type: 0,
    textEn: null,
    permissionType: 0,
    cameraLimited: null,
    cameraNumber: null,
    provinceId: null,
    districtId: null,
    wardId: null,
    phone: null,
    email: null,
    createDate: null,
    lastModifiedDate: null,
    accessKey: null,
    secretKey: null,
    capacity: 0,
  },
  {
    id: "e4ca7ef0b34711eea61bbaf7db86dba7",
    parent: "",
    text: "Ban Giám đốc - Khối 3",
    address: null,
    type: 0,
    textEn: null,
    permissionType: 0,
    cameraLimited: null,
    cameraNumber: null,
    provinceId: null,
    districtId: null,
    wardId: null,
    phone: null,
    email: null,
    createDate: null,
    lastModifiedDate: null,
    accessKey: null,
    secretKey: null,
    capacity: 0,
  },
  {
    id: "8ec712c03d9411ef98223afdc3cd602b",
    parent: "2e259700a5c111ed809502429ea8fc86",
    text: "hanh test",
    address: null,
    type: 0,
    textEn: null,
    permissionType: 0,
    cameraLimited: null,
    cameraNumber: null,
    provinceId: null,
    districtId: null,
    wardId: null,
    phone: null,
    email: null,
    createDate: null,
    lastModifiedDate: null,
    accessKey: null,
    secretKey: null,
    capacity: 0,
  },
  {
    id: "c5db63207c7211efafe8baf7db86dba7",
    parent: "8ec712c03d9411ef98223afdc3cd602b",
    text: "test2709",
    address: null,
    type: 0,
    textEn: null,
    permissionType: 0,
    cameraLimited: null,
    cameraNumber: null,
    provinceId: null,
    districtId: null,
    wardId: null,
    phone: null,
    email: null,
    createDate: null,
    lastModifiedDate: null,
    accessKey: null,
    secretKey: null,
    capacity: 0,
  },
  {
    id: "04cfa420b34b11ee9f95024209624052",
    parent: "",
    text: "Phòng Kiểu dáng và đồ họa - Khối 1",
    address: null,
    type: 0,
    textEn: null,
    permissionType: 0,
    cameraLimited: null,
    cameraNumber: null,
    provinceId: null,
    districtId: null,
    wardId: null,
    phone: null,
    email: null,
    createDate: null,
    lastModifiedDate: null,
    accessKey: null,
    secretKey: null,
    capacity: 0,
  },
  {
    id: "2b6c9700b34b11eea61bbaf7db86dba7",
    parent: "",
    text: "Phòng Quản lý Chất lượng - Khối 3",
    address: null,
    type: 0,
    textEn: null,
    permissionType: 0,
    cameraLimited: null,
    cameraNumber: null,
    provinceId: null,
    districtId: null,
    wardId: null,
    phone: null,
    email: null,
    createDate: null,
    lastModifiedDate: null,
    accessKey: null,
    secretKey: null,
    capacity: 0,
  },
  {
    id: "4edeafc0b34b11eea61bbaf7db86dba7",
    parent: "",
    text: "Trung tâm Nền tảng IoT - Khối 3",
    address: null,
    type: 0,
    textEn: null,
    permissionType: 0,
    cameraLimited: null,
    cameraNumber: null,
    provinceId: null,
    districtId: null,
    wardId: null,
    phone: null,
    email: null,
    createDate: null,
    lastModifiedDate: null,
    accessKey: null,
    secretKey: null,
    capacity: 0,
  },
  {
    id: "5ce8bde0b34b11eeb6150242bae6ed32",
    parent: "",
    text: "Trung tâm mua sắm",
    address: null,
    type: 0,
    textEn: null,
    permissionType: 0,
    cameraLimited: null,
    cameraNumber: null,
    provinceId: null,
    districtId: null,
    wardId: null,
    phone: null,
    email: null,
    createDate: null,
    lastModifiedDate: null,
    accessKey: null,
    secretKey: null,
    capacity: 0,
  },
  {
    id: "d9488900b34c11eea61bbaf7db86dba7",
    parent: "",
    text: "Phòng Tài chính - Khối cơ quan",
    address: null,
    type: 0,
    textEn: null,
    permissionType: 0,
    cameraLimited: null,
    cameraNumber: null,
    provinceId: null,
    districtId: null,
    wardId: null,
    phone: null,
    email: null,
    createDate: null,
    lastModifiedDate: null,
    accessKey: null,
    secretKey: null,
    capacity: 0,
  },
  {
    id: "52f21b603d9311ef98223afdc3cd602b",
    parent: "8ec2641084fd11ed94170242a040d71d",
    text: "123444",
    address: null,
    type: 0,
    textEn: null,
    permissionType: 0,
    cameraLimited: null,
    cameraNumber: null,
    provinceId: null,
    districtId: null,
    wardId: null,
    phone: null,
    email: null,
    createDate: null,
    lastModifiedDate: null,
    accessKey: null,
    secretKey: null,
    capacity: 0,
  },
  {
    id: "eb833360b34a11eebe6f3afdc3cd602b",
    parent: "",
    text: "Trung tâm Khí cụ bay - Khối 1",
    address: null,
    type: 0,
    textEn: null,
    permissionType: 0,
    cameraLimited: null,
    cameraNumber: null,
    provinceId: null,
    districtId: null,
    wardId: null,
    phone: null,
    email: null,
    createDate: null,
    lastModifiedDate: null,
    accessKey: null,
    secretKey: null,
    capacity: 0,
  },
  {
    id: "f0a6be50b34c11eea61bbaf7db86dba7",
    parent: "",
    text: "Trung tâm dịch vụ sau bán hàng",
    address: null,
    type: 0,
    textEn: null,
    permissionType: 0,
    cameraLimited: null,
    cameraNumber: null,
    provinceId: null,
    districtId: null,
    wardId: null,
    phone: null,
    email: null,
    createDate: null,
    lastModifiedDate: null,
    accessKey: null,
    secretKey: null,
    capacity: 0,
  },
];
