export const nodeListWithoutDevices = [
  {
    id: "123",
    parentId: "",
    label: "HNQC",
    groupType: 20,
    deviceList: null,
    address: null,
    auto: true,
    children: [],
  },
  {
    id: "1234",
    parentId: "123",
    label: "HNQC2",
    groupType: 20,
    deviceList: null,
    address: null,
    auto: true,
    children: [],
  },
  {
    id: "1235",
    parentId: "1234",
    label: "HNQC3",
    groupType: 20,
    deviceList: null,
    address: null,
    auto: true,
    children: [],
  },

  {
    id: "12352",
    parentId: "1235",
    label: "HNQC4",
    groupType: 20,
    deviceList: null,
    address: null,
    auto: true,
    children: [],
  },
  {
    id: "142234",
    parentId: "123",
    label: "HNQC332",
    groupType: 20,
    deviceList: null,
    address: null,
    auto: true,
    children: [],
  },
  {
    id: "123512",
    parentId: "1234",
    label: "HNQ33C3",
    groupType: 20,
    deviceList: null,
    address: null,
    auto: true,
    children: [],
  },
];
