import React from "react";
import OfflineIcon from "../Icon/OfflineIcon";
import OnlineIcon from "../Icon/OnlineIcon";
import Recording from "../Icon/Recording";
import FeatureAi from "../components/FeatureAi";
import DeviceStatus from "../components/DeviceStatus";
import DurationIcon from "../Icon/DurationIcon";
import Thumbnail from "../components/Thumbnail";
import ErrorRecord from "../Icon/ErrorRecord";
import NoRecord from "../Icon/NoRecord";
import AiSync from "../components/AiSync";

export const Feature = {
  "Smart Record": {
    label: "Smart Record",
    value: "Smart Record",
  },
  HeatMap: {
    label: "HeatMap",
    value: "HeatMap",
  },
  "Smart Search": {
    label: "Smart Search",
    value: "Smart Search",
  },
  "Parking Count": {
    label: "Parking Count",
    value: "Parking Count",
  },
  "Human Instruction": {
    label: "Human Instruction",
    value: "Human Instruction",
  },
  "Face Recognition": {
    label: "Face Recognition",
    value: "Face Recognition",
  },
};

export const Status = {
  1: {
    label: "Online",
    shortWord: "ON",
    value: 1,
    component: () => {
      return <OnlineIcon />;
    },
  },
  0: {
    label: "Offline",
    shortWord: "OFF",
    value: 0,
    component: () => {
      return <OfflineIcon />;
    },
  },
};
export const RecordStatus = {
  2: {
    label: "Do Not Record",
    value: 2,
    component: ({ width, height }) => {
      return <NoRecord width={width} height={height} />;
    },
  },
  1: {
    label: "Record",
    value: 1,
    component: ({ width, height }) => {
      return <Recording width={width} height={height} />;
    },
  },
  0: {
    label: "Error Record",
    value: 0,
    component: ({ width, height }) => {
      return <ErrorRecord width={width} height={height} />;
    },
  },
};

export const TableHeader = [
  {
    field: "stt",
    name: "#",
    customStyles: {
      minWidth: "60px",
      maxWidth: "60px",
      padding: 10,
      textAlign: "left",
      whiteSpace: "nowrap",
    },
  },
  {
    field: "thumbnail",
    name: "Thumbnail",
    customStyles: {
      minWidth: "130px",
      maxWidth: "130px",
      padding: 10,
      textAlign: "left",
      whiteSpace: "nowrap",
    },
    component: (data) => {
      <Thumbnail data={data} />;
    },
  },
  {
    field: "deviceName",
    name: "Device Name",
    customStyles: {
      minWidth: "130px",
      maxWidth: "130px",
      padding: 10,
      textAlign: "left",
      whiteSpace: "nowrap",
    },
  },
  {
    field: "deviceType",
    name: "Device Type",
    customStyles: {
      minWidth: "100px",
      maxWidth: "100px",
      padding: 10,
      textAlign: "left",
      whiteSpace: "nowrap",
    },
  },
  {
    field: "group",
    name: "Group",
    customStyles: {
      minWidth: "150px",
      maxWidth: "150px",
      padding: 10,
      textAlign: "left",
      whiteSpace: "nowrap",
    },
  },
  {
    field: "status",
    name: "Status",
    customStyles: {
      minWidth: "90px",
      maxWidth: "90px",
      padding: 10,
      textAlign: "left",
      whiteSpace: "nowrap",
    },
    component: (data) => {
      return <DeviceStatus data={data} />;
    },
  },
  {
    field: "recording",
    name: "Recording",
    customStyles: {
      minWidth: "90px",
      maxWidth: "90px",
      padding: 10,
      textAlign: "left",
      whiteSpace: "nowrap",
    },
    component: (data) => {
      const selectRecording = RecordStatus[data.recording];
      return (
        <div
          style={{
            display: "flex",
            alignItems: "center",
            gap: "10px",
          }}
        >
          <selectRecording.component width={20} height={20} />
        </div>
      );
    },
  },
  {
    field: "location",
    name: "Location",
    customStyles: {
      minWidth: "150px",
      maxWidth: "150px",
      padding: 10,
      textAlign: "left",
      whiteSpace: "nowrap",
    },
  },
  {
    field: "lastModify",
    name: "Last Modify",
    customStyles: {
      minWidth: "200px",
      maxWidth: "200px",
      padding: 10,
      textAlign: "left",
      whiteSpace: "nowrap",
    },
  },
  {
    field: "aiFeature",
    name: "Ai Feature",
    customStyles: {
      minWidth: "150px",
      maxWidth: "150px",
      padding: 10,
      textAlign: "left",
      whiteSpace: "nowrap",
    },
    component: (data) => {
      return <FeatureAi data={data} />;
    },
  },
  {
    field: "aiSync",
    name: "AI Sync",
    customStyles: {
      minWidth: "150px",
      maxWidth: "150px",
      padding: 10,
      textAlign: "left",
      whiteSpace: "nowrap",
    },
    component: (data) => {
      return <AiSync data={data} />;
    },
  },
];

export const storagePlanHeader = [
  {
    field: "name",
    name: "Name",
    customStyles: {
      minWidth: "100px",
      maxWidth: "100px",
      padding: 10,
      textAlign: "left",
      whiteSpace: "nowrap",
    },
  },
  {
    field: "period",
    name: "Period",
    customStyles: {
      minWidth: "50px",
      maxWidth: "50px",
      padding: 10,
      textAlign: "left",
      whiteSpace: "nowrap",
    },
  },
  {
    field: "activated",
    name: "Activated",
    customStyles: {
      minWidth: "60px",
      maxWidth: "60px",
      padding: 10,
      textAlign: "left",
      whiteSpace: "nowrap",
    },
  },
  {
    field: "expiration",
    name: "Expiration",
    customStyles: {
      minWidth: "105px",
      maxWidth: "105px",
      padding: 10,
      textAlign: "left",
      whiteSpace: "nowrap",
    },
  },
];

export const headerDeviceStatus = [
  {
    field: "stt",
    name: "#",
    customStyles: {
      minWidth: "40px",
      maxWidth: "40px",
      padding: 10,
      textAlign: "left",
      whiteSpace: "nowrap",
    },
  },
  {
    field: "group",
    name: "Group",
    customStyles: {
      minWidth: "120px",
      maxWidth: "120px",
      padding: 10,
      textAlign: "left",
      whiteSpace: "nowrap",
    },
  },
  {
    field: "offTime",
    name: "Off Time",
    customStyles: {
      minWidth: "90px",
      maxWidth: "90px",
      padding: 10,
      textAlign: "left",
      whiteSpace: "nowrap",
    },
    component: (data) => {
      return <p>{data.offTime}</p>;
    },
  },
  {
    field: "duration",
    name: "Off Time Duration",
    customStyles: {
      minWidth: "90px",
      maxWidth: "90px",
      padding: 10,
      textAlign: "left",
      whiteSpace: "nowrap",
    },
    component: (data) => {
      return (
        <div
          style={{
            display: "flex",
            alignItems: "center",
            flexDirection: "row",
            gap: 10,
          }}
        >
          <DurationIcon />
          <p>{data.duration}</p>
        </div>
      );
    },
  },
];
export const tableData = [
  {
    id: 1,
    thumbnail: null,
    deviceName: "Camera-4",
    deviceType: "IPC",
    group: "LLQ_Building",
    status: 1,
    recording: 2,
    location: "116 Eryn Forges43434343434343434",
    lastModify: "12/27/2023 08:26:25",
    aiFeature: "Parking Count",
    duration: "2h 34m 56s",
    offTime: "12/27/2023 08:26:25",
    sync: true,
    zones: 3,
    line: 1,
    syncStreamOut: false,
  },
  {
    id: 2,
    thumbnail: null,
    deviceName: "Camera- 80",
    deviceType: "IPC",
    group: "LLQ_Building",
    status: 1,
    recording: 1,
    location: "116 Eryn Forges",
    lastModify: "12/27/2023 08:26:25",
    aiFeature: "Parking Count",
    duration: "2h 34m 56s",
    offTime: "12/27/2023 08:26:25",
    sync: true,
    zones: 3,
    line: 1,
    syncStreamOut: true,
  },
  {
    id: 3,
    thumbnail: null,
    deviceName: "Camera- 801",
    deviceType: "IPC",
    group: "LLQ_Building",
    status: 0,
    recording: 2,
    location: "116 Eryn Forges",
    lastModify: "12/27/2023 08:26:25",
    aiFeature: "Parking Count",
    duration: "2h 34m 56s",
    offTime: "12/27/2023 08:26:25",
    sync: true,
    zones: 3,
    line: 1,
    syncStreamOut: true,
  },
  {
    id: 4,
    thumbnail: null,
    deviceName: "Camera- 21",
    deviceType: "IPC",
    group: "LLQ_Building",
    status: 1,
    recording: 0,
    location: "116 Eryn Forges",
    lastModify: "12/27/2023 08:26:25",
    aiFeature: "Parking Count",
    duration: "2h 34m 56s",
    offTime: "12/27/2023 08:26:25",
    sync: true,
    zones: 3,
    line: 1,
    syncStreamOut: false,
  },
  {
    id: 5,
    thumbnail: null,
    deviceName: "Camera- 345",
    deviceType: "IPC",
    group: "LLQ_Building",
    status: 0,
    recording: 1,
    location: "116 Eryn Forges",
    lastModify: "12/27/2023 08:26:25",
    sync: false,
    zones: 3,
    line: 1,
    syncStreamOut: true,
    aiFeature: "Parking Count",
  },
  {
    id: 6,
    thumbnail: null,
    deviceName: "Camera- 80",
    deviceType: "IPC",
    group: "LLQ_Building",
    status: 1,
    recording: 2,
    location: "116 Eryn Forges",
    lastModify: "12/27/2023 08:26:25",
    aiFeature: "Parking Count",
    duration: "2h 34m 56s",
    offTime: "12/27/2023 08:26:25",
    sync: true,
  },
  {
    id: 7,
    thumbnail: null,
    deviceName: "Camera- 11",
    deviceType: "IPC",
    group: "LLQ_Building",
    status: 1,
    recording: 0,
    location: "116 Eryn Forges",
    lastModify: "12/27/2023 08:26:25",
    aiFeature: "Parking Count",
    duration: "2h 34m 56s",
    offTime: "12/27/2023 08:26:25",
    sync: true,
    zones: 3,
    line: 1,
    syncStreamOut: true,
  },
  {
    id: 8,
    thumbnail: null,
    deviceName: "Camera- 80",
    deviceType: "IPC",
    group: "LLQ_Building",
    status: 1,
    recording: 0,
    location: "116 Eryn Forges",
    lastModify: "12/27/2023 08:26:25",
    aiFeature: "Parking Count",
    duration: "2h 34m 56s",
    offTime: "12/27/2023 08:26:25",
    sync: false,
  },
  {
    id: 9,
    thumbnail: null,
    deviceName: "Camera- 34",
    deviceType: "IPC",
    group: "LLQ_Building",
    status: 1,
    recording: 0,
    location: "116 Eryn Forges",
    lastModify: "12/27/2023 08:26:25",
    aiFeature: "Parking Count",
    duration: "2h 34m 56s",
    offTime: "12/27/2023 08:26:25",
    sync: true,
    zones: 3,
    line: 1,
    syncStreamOut: false,
  },
  {
    id: 10,
    thumbnail: null,
    deviceName: "Camera- 80",
    deviceType: "IPC",
    group: "LLQ_Building",
    status: 1,
    recording: 0,
    location: "116 Eryn Forges",
    lastModify: "12/27/2023 08:26:25",
    aiFeature: "Parking Count",
    duration: "2h 34m 56s",
    offTime: "12/27/2023 08:26:25",
    sync: true,
    zones: 3,
    line: 1,
    syncStreamOut: true,
  },
  {
    id: 11,
    thumbnail: null,
    deviceName: "Camera- 80",
    deviceType: "IPC",
    group: "LLQ_Building",
    status: 1,
    recording: 0,
    location: "116 Eryn Forges",
    lastModify: "12/27/2023 08:26:25",
    aiFeature: "Parking Count",
    duration: "2h 34m 56s",
    offTime: "12/27/2023 08:26:25",
    sync: false,
    zones: 3,
    line: 1,
    syncStreamOut: true,
  },
  {
    id: 12,
    thumbnail: null,
    deviceName: "Camera- 80",
    deviceType: "IPC",
    group: "LLQ_Building",
    status: 1,
    recording: 0,
    location: "116 Eryn Forges",
    lastModify: "12/27/2023 08:26:25",
    aiFeature: "Parking Count",
    duration: "2h 34m 56s",
    offTime: "12/27/2023 08:26:25",
    sync: true,
  },
  {
    id: 13,
    thumbnail: null,
    deviceName: "Camera- 80",
    deviceType: "IPC",
    group: "LLQ_Building",
    status: 1,
    recording: 0,
    location: "116 Eryn Forges",
    lastModify: "12/27/2023 08:26:25",
    aiFeature: "Parking Count",
    duration: "2h 34m 56s",
    offTime: "12/27/2023 08:26:25",
    sync: true,
    zones: 3,
    line: 1,
    syncStreamOut: true,
  },
  {
    id: 14,
    thumbnail: null,
    deviceName: "Camera- 80",
    deviceType: "IPC",
    group: "LLQ_Building",
    status: 1,
    recording: 0,
    location: "116 Eryn Forges",
    lastModify: "12/27/2023 08:26:25",
    aiFeature: "Parking Count",
    duration: "2h 34m 56s",
    offTime: "12/27/2023 08:26:25",
    sync: true,
    zones: 3,
    line: 1,
    syncStreamOut: true,
  },
  {
    id: 15,
    thumbnail: null,
    deviceName: "Camera- 80",
    deviceType: "IPC",
    group: "LLQ_Building",
    status: 1,
    recording: 0,
    location: "116 Eryn Forges",
    lastModify: "12/27/2023 08:26:25",
    aiFeature: "Parking Count",
    duration: "2h 34m 56s",
    offTime: "12/27/2023 08:26:25",
    sync: true,
    zones: 3,
    line: 1,
    syncStreamOut: true,
  },
  {
    id: 16,
    thumbnail: null,
    deviceName: "Camera- 80",
    deviceType: "IPC",
    group: "LLQ_Building",
    status: 1,
    recording: 0,
    location: "116 Eryn Forges",
    lastModify: "12/27/2023 08:26:25",
    aiFeature: "Parking Count",
    duration: "2h 34m 56s",
    offTime: "12/27/2023 08:26:25",
    sync: true,
    zones: 3,
    line: 1,
    syncStreamOut: true,
  },
  {
    id: 17,
    thumbnail: null,
    deviceName: "Camera- 80",
    deviceType: "IPC",
    group: "LLQ_Building",
    status: 1,
    recording: 0,
    location: "116 Eryn Forges",
    lastModify: "12/27/2023 08:26:25",
    aiFeature: "Parking Count",
    duration: "2h 34m 56s",
    offTime: "12/27/2023 08:26:25",
    sync: false,
    zones: 3,
    line: 1,
    syncStreamOut: true,
  },
  {
    id: 18,
    thumbnail: null,
    deviceName: "Camera- 80",
    deviceType: "IPC",
    group: "LLQ_Building",
    status: 1,
    recording: 0,
    location: "116 Eryn Forges",
    lastModify: "12/27/2023 08:26:25",
    aiFeature: "Parking Count",
    duration: "2h 34m 56s",
    offTime: "12/27/2023 08:26:25",
    sync: true,
    zones: 3,
    line: 1,
    syncStreamOut: true,
  },
  {
    id: 19,
    thumbnail: null,
    deviceName: "Camera- 80",
    deviceType: "IPC",
    group: "LLQ_Building",
    status: 1,
    recording: 0,
    location: "116 Eryn Forges",
    lastModify: "12/27/2023 08:26:25",
    aiFeature: "Parking Count",
    duration: "2h 34m 56s",
    offTime: "12/27/2023 08:26:25",
    sync: true,
    zones: 3,
    line: 1,
    syncStreamOut: true,
  },
  {
    id: 20,
    thumbnail: null,
    deviceName: "Camera- 80",
    deviceType: "IPC",
    group: "LLQ_Building",
    status: 1,
    recording: 0,
    location: "116 Eryn Forges",
    lastModify: "12/27/2023 08:26:25",
    aiFeature: "Parking Count",
    duration: "2h 34m 56s",
    offTime: "12/27/2023 08:26:25",
    sync: true,
    zones: 3,
    line: 1,
    syncStreamOut: false,
  },
  {
    id: 21,
    thumbnail: null,
    deviceName: "Camera- 80",
    deviceType: "IPC",
    group: "LLQ_Building",
    status: 1,
    recording: 0,
    location: "116 Eryn Forges",
    lastModify: "12/27/2023 08:26:25",
    aiFeature: "Parking Count",
    duration: "2h 34m 56s",
    offTime: "12/27/2023 08:26:25",
    sync: true,
    zones: 3,
    line: 1,
    syncStreamOut: true,
  },
  {
    id: 22,
    thumbnail: null,
    deviceName: "Camera- 80",
    deviceType: "IPC",
    group: "LLQ_Building",
    status: 1,
    recording: 0,
    location: "116 Eryn Forges",
    lastModify: "12/27/2023 08:26:25",
    aiFeature: "Parking Count",
    duration: "2h 34m 56s",
    offTime: "12/27/2023 08:26:25",
    sync: true,
    zones: 3,
    line: 1,
    syncStreamOut: true,
  },
  {
    id: 23,
    thumbnail: null,
    deviceName: "Camera- 80",
    deviceType: "IPC",
    group: "LLQ_Building",
    status: 1,
    recording: 0,
    location: "116 Eryn Forges",
    lastModify: "12/27/2023 08:26:25",
    aiFeature: "Parking Count",
    duration: "2h 34m 56s",
    offTime: "12/27/2023 08:26:25",
    sync: false,
    zones: 3,
    line: 1,
    syncStreamOut: true,
  },
];

export const DeviceType = {
  IPC: {
    label: "IPC",
    value: "IPC",
  },
  NVR: {
    label: "NVR",
    value: "NVR",
  },
  "App Screen": {
    label: "App Screen",
    value: "App Screen",
  },
};

export const headerDeviceFilterArr = [
  {
    width: 200,
    btnText: "AI Feature",
    titleDropdownText: "All Feature",
    key: "aiFeature",
    list: Object.values(Feature),
    type: "select_multiple",
  },
  {
    width: 200,
    btnText: "Device Type",
    titleDropdownText: "All Device Type",
    key: "deviceType",
    list: Object.values(DeviceType),
    type: "select_multiple",
  },
  {
    width: 200,
    btnText: "Status",
    titleDropdownText: "All Status",
    key: "status",
    list: Object.values(Status),
    listObject: Status,
    type: "select",
  },
  {
    width: 200,
    btnText: "Recording",
    titleDropdownText: "All Recording Status",
    key: "recording",
    list: Object.values(RecordStatus),
    listObject: RecordStatus,
    type: "select",
  },
];

export const lowerCaseStringCustom = (numberChecked, originalString) => {
  return `${numberChecked ? numberChecked : "All"} ${originalString}`;
};

export const worksheetColumns = [
  { header: "Group", key: "group", width: 25 },
  { header: "Device Name", key: "deviceName", width: 25 },
  { header: "Device Type", key: "deviceType", width: 25 },
  { header: "Stream Type", key: "streamType", width: 25 },
  { header: "Feature Type", key: "featureType", width: 25 },
  { header: "Location", key: "location", width: 25 },
  { header: "Note", key: "note", width: 25 },
  { header: "Vision Mode", key: "visionMode", width: 25 },
  { header: "Ai Processing Modes", key: "aiProcessingModes", width: 25 },
  { header: "Ai Type", key: "aiType", width: 25 },
  { header: "Ai Feature", key: "aiFeature", width: 25 },
  { header: "Private Order", key: "privateOrder", width: 25 },
  {
    header: "Enable Private Camera Stream",
    key: "enablePrivateCameraStream",
    width: 35,
  },
  { header: "Private Primary Stream", key: "privatePrimaryStream", width: 35 },
  {
    header: "Private Secondary Stream",
    key: "privateSecondaryStream",
    width: 35,
  },
  { header: "Public Order", key: "publicOrder", width: 25 },
  {
    header: "Enable Public Camera Stream",
    key: "enablePublicCameraStream",
    width: 35,
  },
  { header: "Public Primary Stream", key: "publicPrimaryStream", width: 25 },
  {
    header: "Public Secondary Stream",
    key: "publicSecondaryStream",
    width: 35,
  },
  { header: "Visual AI Order", key: "visualAIOrder", width: 25 },
  {
    header: "Enable Visual AI Camera Stream",
    key: "enableVisualAICameraStream",
    width: 35,
  },
  { header: "Enable AI Streaming Out", key: "enableAIStreamingOut", width: 35 },
  {
    header: "Visual AI Primary Stream",
    key: "visualAIPrimaryStream",
    width: 35,
  },
  {
    header: "Visual AI Secondary Stream",
    key: "visialAISecondaryStream",
    width: 35,
  },
  { header: "Access Key", key: "accessKey", width: 25 },
  { header: "Secret Key", key: "secretKey", width: 25 },
  { header: "Recording", key: "recording", width: 25 },
  { header: "Recording Schedule", key: "recordingSchedule", width: 25 },
  { header: "Zones", key: "zones", width: 25 },
  { header: "Storage Plan", key: "storagePlan", width: 25 },
  { header: "Lines", key: "lines", width: 25 },
  { header: "Presets", key: "presets", width: 25 },
  { header: "Tours", key: "tours", width: 25 },
  { header: "Config Primary Stream", key: "configPrimaryStream", width: 35 },
  {
    header: "Config Secondary Stream",
    key: "configSecondaryStream",
    width: 35,
  },
];

export const rowObject = {
  group: "",
  deviceName: "",
  deviceType: "",
  streamType: "",
  featureType: "",
  location: "",
  note: "",
  visionMode: "",
  aiProcessingModes: "",
  aiType: "",
  aiFeature: "",
  privateOrder: "",
  enablePrivateCameraStream: "",
  privatePrimaryStream: "",
  privateSecondaryStream: "",
  publicOrder: "",
  enablePublicCameraStream: "",
  publicPrimaryStream: "",
  publicSecondaryStream: "",
  visualAIOrder: "",
  enableVisualAICameraStream: "",
  enableAIStreamingOut: "",
  visualAIPrimaryStream: "",
  visialAISecondaryStream: "",
  accessKey: "",
  secretKey: "",
  recording: "",
  recordingSchedule: "",
  zones: "",
  storagePlan: "",
  lines: "",
  presets: "",
  tours: "",
  configPrimaryStream: "",
  configSecondaryStream: "",
};
export const days = ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"];
export const hours = Array.from(Array(25)).map((_, indx) => indx);

export const listDevice = Array.from(Array(10)).map((_, indx) => ({
  label: `test ${indx}`,
  id: indx,
  ip: "179.229.40.98",
  vendor: "AXIS",
  added: indx % 2 === 0,
  port: 80,
  firmware: "1.2.3",
  private: {
    primaryStream: `private primaryStream ${indx}`,
    secondaryStream: `private secondaryStream ${indx}`,
  },
  public: {
    primaryStream: `public primaryStream ${indx}`,
    secondaryStream: `public secondaryStream ${indx}`,
  },
  visualAI: {
    primaryStream: `visualAI primaryStream ${indx}`,
    secondaryStream: `visualAI secondaryStream ${indx}`,
  },
}));
