import React from "react";
import OfflineIcon from "../Icon/OfflineIcon";
import OnlineIcon from "../Icon/OnlineIcon";
import Recording from "../Icon/Recording";
import NoRecording from "../Icon/NoRecording";

export const TableHeader = [
  {
    field: "stt",
    name: "#",
    customStyles: {
      minWidth: "40px",
      maxWidth: "40px",
      padding: 10,
      textAlign: "left",
      whiteSpace: "nowrap",
    },
  },
  {
    field: "thumbnail",
    name: "Thumbnail",
    customStyles: {
      minWidth: "150px",
      maxWidth: "150px",  
      padding: 10,
      textAlign: "left",
      whiteSpace: "nowrap",
    },
  },
  {
    field: "deviceName",
    name: "Device Name",
    customStyles: {
      minWidth: "150px",
      maxWidth: "200px",
      padding: 10,
      textAlign: "left",
      whiteSpace: "nowrap",
    },
  },
  {
    field: "deviceType",
    name: "Device Type",
    customStyles: {
      minWidth: "100px",
      maxWidth: "200px",
      padding: 10,
      textAlign: "left",
      whiteSpace: "nowrap",
    },
  },
  {
    field: "group",
    name: "Group",
    customStyles: {
      minWidth: "150px",
      maxWidth: "200px",
      padding: 10,
      textAlign: "left",
      whiteSpace: "nowrap",
    },
  },
  {
    field: "status",
    name: "Status",
    customStyles: {
      minWidth: "90px",
      maxWidth: "200px",
      padding: 10,
      textAlign: "left",
      whiteSpace: "nowrap",
    },
  },
  {
    field: "recording",
    name: "Recording",
    customStyles: {
      minWidth: "90px",
      maxWidth: "200px",
      padding: 10,
      textAlign: "left",
      whiteSpace: "nowrap",
    },
  },
  {
    field: "location",
    name: "Location",
    customStyles: {
      minWidth: "150px",
      maxWidth: "150px",
      padding: 10,
      textAlign: "left",
      whiteSpace: "nowrap",
    },
  },
  {
    field: "lastModify",
    name: "Last Modify",
    customStyles: {
      minWidth: "200px",
      maxWidth: "200px",
      padding: 10,
      textAlign: "left",
      whiteSpace: "nowrap",
    },
  },
  {
    field: "aiFeature",
    name: "Ai Feature",
    customStyles: {
      minWidth: "350px",
      maxWidth: "350px",
      padding: 10,
      textAlign: "left",
      whiteSpace: "nowrap",
    },
  },
];
export const tableData = [
  {
    id: 1,
    thumbnail: null,
    deviceName: "Camera- 80",
    deviceType: "IPC",
    group: "LLQ_Building",
    status: 1,
    recording: 0,
    location: "116 Eryn Forges",
    lastModify: "12/27/2023 08:26:25",
    aiFeature: "Parking Count,HeatMap,Face Recognition",
  },
  {
    id: 2,
    thumbnail: null,
    deviceName: "Camera- 80",
    deviceType: "IPC",
    group: "LLQ_Building",
    status: 1,
    recording: 0,
    location: "116 Eryn Forges",
    lastModify: "12/27/2023 08:26:25",
    aiFeature: "Parking Count,HeatMap,Face Recognition",
  },
  {
    id: 3,
    thumbnail: null,
    deviceName: "Camera- 80",
    deviceType: "IPC",
    group: "LLQ_Building",
    status: 1,
    recording: 0,
    location: "116 Eryn Forges",
    lastModify: "12/27/2023 08:26:25",
    aiFeature: "Parking Count,HeatMap,Face Recognition",
  },
  {
    id: 4,
    thumbnail: null,
    deviceName: "Camera- 80",
    deviceType: "IPC",
    group: "LLQ_Building",
    status: 1,
    recording: 0,
    location: "116 Eryn Forges",
    lastModify: "12/27/2023 08:26:25",
    aiFeature: "Parking Count,HeatMap,Face Recognition",
  },
  {
    id: 5,
    thumbnail: null,
    deviceName: "Camera- 80",
    deviceType: "IPC",
    group: "LLQ_Building",
    status: 1,
    recording: 0,
    location: "116 Eryn Forges",
    lastModify: "12/27/2023 08:26:25",
    aiFeature: "Parking Count,HeatMap,Face Recognition",
  },
  {
    id: 6,
    thumbnail: null,
    deviceName: "Camera- 80",
    deviceType: "IPC",
    group: "LLQ_Building",
    status: 1,
    recording: 0,
    location: "116 Eryn Forges",
    lastModify: "12/27/2023 08:26:25",
    aiFeature: "Parking Count,HeatMap,Face Recognition",
  },
  {
    id:7,
    thumbnail: null,
    deviceName: "Camera- 80",
    deviceType: "IPC",
    group: "LLQ_Building",
    status: 1,
    recording: 0,
    location: "116 Eryn Forges",
    lastModify: "12/27/2023 08:26:25",
    aiFeature: "Parking Count,HeatMap,Face Recognition",
  },
  {
    id: 8,
    thumbnail: null,
    deviceName: "Camera- 80",
    deviceType: "IPC",
    group: "LLQ_Building",
    status: 1,
    recording: 0,
    location: "116 Eryn Forges",
    lastModify: "12/27/2023 08:26:25",
    aiFeature: "Parking Count,HeatMap,Face Recognition",
  },
  {
    id: 9,
    thumbnail: null,
    deviceName: "Camera- 80",
    deviceType: "IPC",
    group: "LLQ_Building",
    status: 1,
    recording: 0,
    location: "116 Eryn Forges",
    lastModify: "12/27/2023 08:26:25",
    aiFeature: "Parking Count,HeatMap,Face Recognition",
  },
  {
    id: 10,
    thumbnail: null,
    deviceName: "Camera- 80",
    deviceType: "IPC",
    group: "LLQ_Building",
    status: 1,
    recording: 0,
    location: "116 Eryn Forges",
    lastModify: "12/27/2023 08:26:25",
    aiFeature: "Parking Count,HeatMap,Face Recognition",
  },
  {
    id: 11,
    thumbnail: null,
    deviceName: "Camera- 80",
    deviceType: "IPC",
    group: "LLQ_Building",
    status: 1,
    recording: 0,
    location: "116 Eryn Forges",
    lastModify: "12/27/2023 08:26:25",
    aiFeature: "Parking Count,HeatMap,Face Recognition",
  },
  {
    id: 12,
    thumbnail: null,
    deviceName: "Camera- 80",
    deviceType: "IPC",
    group: "LLQ_Building",
    status: 1,
    recording: 0,
    location: "116 Eryn Forges",
    lastModify: "12/27/2023 08:26:25",
    aiFeature: "Parking Count,HeatMap,Face Recognition",
  },
  {
    id: 13,
    thumbnail: null,
    deviceName: "Camera- 80",
    deviceType: "IPC",
    group: "LLQ_Building",
    status: 1,
    recording: 0,
    location: "116 Eryn Forges",
    lastModify: "12/27/2023 08:26:25",
    aiFeature: "Parking Count,HeatMap,Face Recognition",
  },
  {
    id: 14,
    thumbnail: null,
    deviceName: "Camera- 80",
    deviceType: "IPC",
    group: "LLQ_Building",
    status: 1,
    recording: 0,
    location: "116 Eryn Forges",
    lastModify: "12/27/2023 08:26:25",
    aiFeature: "Parking Count,HeatMap,Face Recognition",
  },
  {
    id: 15,
    thumbnail: null,
    deviceName: "Camera- 80",
    deviceType: "IPC",
    group: "LLQ_Building",
    status: 1,
    recording: 0,
    location: "116 Eryn Forges",
    lastModify: "12/27/2023 08:26:25",
    aiFeature: "Parking Count,HeatMap,Face Recognition",
  },
  {
    id: 16,
    thumbnail: null,
    deviceName: "Camera- 80",
    deviceType: "IPC",
    group: "LLQ_Building",
    status: 1,
    recording: 0,
    location: "116 Eryn Forges",
    lastModify: "12/27/2023 08:26:25",
    aiFeature: "Parking Count,HeatMap,Face Recognition",
  },
  {
    id: 17,
    thumbnail: null,
    deviceName: "Camera- 80",
    deviceType: "IPC",
    group: "LLQ_Building",
    status: 1,
    recording: 0,
    location: "116 Eryn Forges",
    lastModify: "12/27/2023 08:26:25",
    aiFeature: "Parking Count,HeatMap,Face Recognition",
  },
  {
    id: 18,
    thumbnail: null,
    deviceName: "Camera- 80",
    deviceType: "IPC",
    group: "LLQ_Building",
    status: 1,
    recording: 0,
    location: "116 Eryn Forges",
    lastModify: "12/27/2023 08:26:25",
    aiFeature: "Parking Count,HeatMap,Face Recognition",
  },
  {
    id: 19,
    thumbnail: null,
    deviceName: "Camera- 80",
    deviceType: "IPC",
    group: "LLQ_Building",
    status: 1,
    recording: 0,
    location: "116 Eryn Forges",
    lastModify: "12/27/2023 08:26:25",
    aiFeature: "Parking Count,HeatMap,Face Recognition",
  },
  {
    id: 20,
    thumbnail: null,
    deviceName: "Camera- 80",
    deviceType: "IPC",
    group: "LLQ_Building",
    status: 1,
    recording: 0,
    location: "116 Eryn Forges",
    lastModify: "12/27/2023 08:26:25",
    aiFeature: "Parking Count,HeatMap,Face Recognition",
  },
  {
    id: 21,
    thumbnail: null,
    deviceName: "Camera- 80",
    deviceType: "IPC",
    group: "LLQ_Building",
    status: 1,
    recording: 0,
    location: "116 Eryn Forges",
    lastModify: "12/27/2023 08:26:25",
    aiFeature: "Parking Count,HeatMap,Face Recognition",
  },
  {
    id: 22,
    thumbnail: null,
    deviceName: "Camera- 80",
    deviceType: "IPC",
    group: "LLQ_Building",
    status: 1,
    recording: 0,
    location: "116 Eryn Forges",
    lastModify: "12/27/2023 08:26:25",
    aiFeature: "Parking Count,HeatMap,Face Recognition",
  },
  {
    id: 23,
    thumbnail: null,
    deviceName: "Camera- 80",
    deviceType: "IPC",
    group: "LLQ_Building",
    status: 1,
    recording: 0,
    location: "116 Eryn Forges",
    lastModify: "12/27/2023 08:26:25",
    aiFeature: "Parking Count,HeatMap,Face Recognition",
  },
  
  
];
export const Status = {
  1: {
    label: "Online",
    value: 1,
    component: () => {
      return <OnlineIcon />;
    },
  },
  0: {
    label: "Offline",
    value: 0,
    component: () => {
      return <OfflineIcon />;
    },
  },
};

export const DeviceType = {
  IPC: {
    label: "IPC",
    value: "IPC",
  },
  NVR: {
    label: "NVR",
    value: "NVR",
  },
  "App Screen": {
    label: "App Screen",
    value: "App Screen",
  },
};

export const RecordStatus = {
  1: {
    label: "Record",
    value: 1,
    component: () => {
      return <Recording />;
    },
  },
  0: {
    label: "Do Not Record",
    value: 0,
    component: () => {
      return <NoRecording />;
    },
  },
};

export const Feature = {
  "Smart Record": {
    label: "Smart Record",
    value: "Smart Record",
  },
  HeatMap: {
    label: "HeatMap",
    value: "HeatMap",
  },
  "Smart Search": {
    label: "Smart Search",
    value: "Smart Search",
  },
  "Parking Count": {
    label: "Parking Count",
    value: "Parking Count",
  },
  "Human Instruction": {
    label: "Human Instruction",
    value: "Human Instruction",
  },
  "Face Recognition": {
    label: "Face Recognition",
    value: "Face Recognition",
  },
};

export const headerDeviceFilterArr = [
  {
    width: 200,
    btnText: "AI Feature",
    titleDropdownText: "All Feature",
    key: "aiFeature",
    list: Object.values(Feature),
    type: "select_multiple",
  },
  {
    width: 200,
    btnText: "Device Type",
    titleDropdownText: "All Device Type",
    key: "deviceType",
    list: Object.values(DeviceType),
    type: "select_multiple",
  },
  {
    width: 200,
    btnText: "Status",
    titleDropdownText: "All Status",
    key: "status",
    list: Object.values(Status),
    listObject: Status,
    type: "select",
  },
  {
    width: 200,
    btnText: "Recording",
    titleDropdownText: "All Recording Status",
    key: "recording",
    list: Object.values(RecordStatus),
    listObject: RecordStatus,
    type: "select",
  },
];

export const lowerCaseStringCustom = (numberChecked, originalString) => {
  return `${numberChecked ? numberChecked : "All"} ${originalString}`;
};
